[build]
command='npm run build'
publish='site'
functions='functions'

[dev]
framework='#static'
publish='site'

[[redirects]]
from='/foo/*'
to='.netlify/functions/something'
status=200

[[redirects]]
from='/wow/*'
to='.netlify/functions/something?special=:splat&yes=no'
status=200
